### ISSUE TITLE
An exception occurred during a WebClient request.

### ISSUE THREAD

**Issue by jammy570** [UNT-CAS/ePOwerShell#17]
First, THANKS for doing this. You are awesome.

I'm using ePO 5.9.0.  Got the module imported. Set up ePOwerShellServer via the Quickstart instructions and get this error below. Is there any other easy setup that I'm missing?

PS C:\> Find-ePOwerShellComputerSystem $env:ComputerName
Failed with unknown error: Exception calling "DownloadString" with "1" argument(s): "An exception occurred during a WebClient request."
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\ePOwerShell\Private\Invoke-ePOwerShellWebClient.ps1:36 char:9
+         Throw ('Failed with unknown error: {0}' -f $_.Exception.Messa ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed with unk...lient request.":String) [], RuntimeException
    + FullyQualifiedErrorId : Failed with unknown error: Exception calling "DownloadString" with "1" argument(s): "An exception occurred during a WebClient request."

**Comment by jammy570** [comment]
Umm... nevermind. I figured it out.

**Comment by marranaga** [comment]
Glad you were able to figure it out! Let us know if there's anything else you'd like help with.

**Comment by a13xchan** [comment]
I am having same issue and not using a domain in my username
