### ISSUE TITLE
An exception occurred during a WebClient request. Domain Auth

### ISSUE THREAD

**Issue by a13xchan** [UNT-CAS/ePOwerShell#18]
Seem to have a strange issue with auth with epo i am receiving 

Failed with unknown error: Exception calling "DownloadString" with "1" argument(s): "An
   exception occurred during a WebClient request."

It seems to occur when i try and auth to the epo server using domain creds (not including the domain name). Username contains special chars such as -

**Comment by arlindovcosta** [comment]
I am also having this same issue. Is there any workaround for this?

**Comment by arlindovcosta** [comment]
Using Server = 'https://[epo server name or IP]' instead of Server = '[epo server name or IP]' resolved the issue for me

**Comment by marranaga** [comment]
@a13xchan and @arlindovcosta, terribly sorry, I didn't notice the notifications for this issue. Arlindovcosta is correct, the code does require the complete url for the ePO server. The next update to this module will include an autofill for the URL to confirm https, as well as a test for the credentials, to make sure they can auth to your ePO server.

**Comment by marranaga** [comment]
@a13xchan and @arlindovcosta, with the new version of ePO, are you still experiencing this issue?

**Comment by a13xchan** [comment]
Issue has been resolved after figuring out what it was actually asking for.
