### ISSUE TITLE
Module uses wrong variable to check for AllowSelfSignedCerts

### ISSUE THREAD

**Issue by hjbotha** [UNT-CAS/ePOwerShell#25]
I think I've identified an issue. When the module checks whether self-signed certs should be allowed, it's looking for $Script:ePOwerShell.AllowSelfSignedCerts, but the variable is actually $Script:ePOwerShell.AllowSelfSigned.

The name gets changed at [ePOwerShell/ePOwerShell/Private/Initialize-ePOConfig.ps1:57](https://github.com/UNT-CAS/ePOwerShell/blob/2f8b0d5048812356270b403db834c235a2cdcd4c/ePOwerShell/Private/Initialize-ePOConfig.ps1#L53-L58), and gets checked at [ePOwerShell/Private/Invoke-ePORequest.ps1:61](https://github.com/UNT-CAS/ePOwerShell/blob/2f8b0d5048812356270b403db834c235a2cdcd4c/ePOwerShell/Private/Invoke-ePORequest.ps1#L61)

This results in self-signed certs failing.

**Comment by marranaga** [comment]
Thanks @hjbotha, this was a definite oversight. I'll get this patched quickly.

**Comment by marranaga** [comment]
Patched with version 2.1.1
